/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.4).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.example.api;

import com.example.model.ItemList;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

import javax.validation.Valid;
import javax.validation.constraints.*;

@javax.annotation.Generated(value = "com.example.codegen.v3.generators.java.SpringCodegen", date = "2019-01-21T14:54:46.412Z[GMT]")
@Api(value = "search", description = "the search API")
public interface SearchApi {

    @ApiOperation(value = "some text", nickname = "searchGet", notes = "some description", response = ItemList.class, tags={  })
    @ApiResponses(value = {
        @ApiResponse(code = 200, message = "dwsc", response = ItemList.class) })
    @RequestMapping(value = "/search",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<ItemList> searchGet(@NotNull @ApiParam(value = "string for search query", required = true) @Valid @RequestParam(value = "searchString", required = true) String searchString, @NotNull @ApiParam(value = "number of page", required = true) @Valid @RequestParam(value = "pageNumber", required = true) Integer pageNumber, @NotNull @ApiParam(value = "size of page to return", required = true) @Valid @RequestParam(value = "pageSize", required = true) Integer pageSize);

}
